"""
Train an MLP surrogate on the two-particle spring system dataset
(data/particle_dataset.npz, generated by data/generate_particle_data.py).

Learns the one-step map:
    [x1,y1,vx1,vy1,x2,y2,vx2,vy2]_t -> [x1,y1,vx1,vy1,x2,y2,vx2,vy2]_(t+1)

Same training philosophy as models/train.py (Step 2): standardized
inputs/outputs (normalizer fit on train split only, reused for outputs),
Adam + MSE, validation-loss-based checkpoint selection, fixed seed.

Training configuration (fixed, for reproducibility):
    seed              = 42
    train/val/test    = 70% / 15% / 15% (already split by
                        data/generate_particle_data.py)
    normalization     = standardize all 8 dims using TRAIN-set mean/std,
                        same normalizer reused for inputs and targets
    architecture      = MLP: 8 -> 16 -> 16 -> 8, ReLU activations
                        (deliberately smaller than a first "8->128->128->8"
                        attempt: exact Marabou verification of the 128-hidden
                        version did not finish within minutes even with 4
                        parallel workers, while this 16-hidden version
                        verifies in seconds -- see the README's
                        "verification scalability" note)
    loss              = MSE
    optimizer         = Adam, lr=1e-3
    batch size        = 256
    epochs            = 200
    model selection   = checkpoint with lowest validation loss

Run from the verified-scientific-ml/ directory:
    python -m models.train_particle
"""

from __future__ import annotations

import os

import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from models.normalization import Normalizer
from models.particle_mlp import ParticleMLP

SEED = 42
HIDDEN_DIM = 16
LEARNING_RATE = 1e-3
BATCH_SIZE = 256
EPOCHS = 200

MODELS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(MODELS_DIR)
DATA_PATH = os.path.join(ROOT_DIR, "data", "particle_dataset.npz")
CHECKPOINT_DIR = os.path.join(MODELS_DIR, "checkpoints")
PLOTS_DIR = os.path.join(MODELS_DIR, "plots")


def set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)


def main() -> None:
    set_seed(SEED)
    os.makedirs(CHECKPOINT_DIR, exist_ok=True)
    os.makedirs(PLOTS_DIR, exist_ok=True)

    data = np.load(DATA_PATH)
    train_x = data["train_states_t"].astype(np.float64)
    train_y = data["train_states_tp1"].astype(np.float64)
    val_x = data["val_states_t"].astype(np.float64)
    val_y = data["val_states_tp1"].astype(np.float64)

    normalizer = Normalizer.fit(train_x)
    normalizer.save(os.path.join(CHECKPOINT_DIR, "particle_normalizer.npz"))

    def to_tensor(x: np.ndarray, y: np.ndarray):
        x_n = normalizer.transform(x).astype(np.float32)
        y_n = normalizer.transform(y).astype(np.float32)
        return torch.from_numpy(x_n), torch.from_numpy(y_n)

    train_x_t, train_y_t = to_tensor(train_x, train_y)
    val_x_t, val_y_t = to_tensor(val_x, val_y)

    # Save metadata needed by evaluate_particle.py / verification (test split
    # itself is loaded directly from data/particle_dataset.npz).
    np.savez(
        os.path.join(CHECKPOINT_DIR, "particle_splits.npz"),
        k=float(data["k"]), rest_length=float(data["rest_length"]),
        m1=float(data["m1"]), m2=float(data["m2"]), dt=float(data["dt"]),
        seed=SEED,
        domain_lower=data["domain_lower"], domain_upper=data["domain_upper"],
        state_names=data["state_names"],
    )

    model = ParticleMLP(hidden_dim=HIDDEN_DIM)
    optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
    loss_fn = nn.MSELoss()

    train_loader = DataLoader(
        TensorDataset(train_x_t, train_y_t),
        batch_size=BATCH_SIZE,
        shuffle=True,
        generator=torch.Generator().manual_seed(SEED),
    )

    train_losses = []
    val_losses = []
    best_val_loss = float("inf")
    best_state = None

    for epoch in range(1, EPOCHS + 1):
        model.train()
        epoch_loss = 0.0
        n_batches = 0
        for xb, yb in train_loader:
            optimizer.zero_grad()
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            n_batches += 1
        train_loss = epoch_loss / n_batches

        model.eval()
        with torch.no_grad():
            val_loss = loss_fn(model(val_x_t), val_y_t).item()

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = {name: p.clone() for name, p in model.state_dict().items()}

        if epoch == 1 or epoch % 20 == 0:
            print(f"epoch {epoch:4d}  train_loss={train_loss:.6e}  val_loss={val_loss:.6e}")

    model.load_state_dict(best_state)

    torch.save(model.state_dict(), os.path.join(CHECKPOINT_DIR, "particle_mlp.pt"))
    np.savez(
        os.path.join(CHECKPOINT_DIR, "particle_loss_history.npz"),
        train_losses=np.array(train_losses),
        val_losses=np.array(val_losses),
        best_val_loss=best_val_loss,
    )

    print(f"\nBest validation loss (normalized MSE): {best_val_loss:.6e}")
    print(f"Saved model to {os.path.join(CHECKPOINT_DIR, 'particle_mlp.pt')}")
    print(f"Saved normalizer to {os.path.join(CHECKPOINT_DIR, 'particle_normalizer.npz')}")


if __name__ == "__main__":
    main()
